version: '3.4'

services:
  web:
    build:
      context: .
    image: score
    ports:
      - '80:80'
    env_file: .env
    healthcheck:
      test: ./health_check.sh
      interval: 1m30s
      start_period: 10s
      timeout: 3s
      retries: 3
